//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_PowerDept.Admin {
    
    
    public partial class ITEM_WISEISSUED {
        
        /// <summary>
        /// Issue_report_Excel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IMS_PowerDept.UserControls.Issue_report_Excel Issue_report_Excel1;
    }
}
