//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_PowerDept.CentralStore {
    
    
    public partial class ItemsListInventory {
        
        /// <summary>
        /// ItemsListInventoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IMS_PowerDept.UserControls.ItemsListInventoryControl ItemsListInventoryControl;
    }
}
